import type { Metadata } from "next";
import "./globals.css";
import NavHeader from "./ui/nav";
import { inter } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`text-[#000000] ${inter.className}`}>
        <div className="min-h-dvh flex flex-col">
          <NavHeader />
          {children}
        </div>
      </body>
    </html>
  );
}
